# Generated by Django 6.0.4 on 2026-04-28 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Identificador URL-safe da clínica. Usado no header `X-Clinic-Slug` para resolver o tenant em requests do painel.', max_length=80, unique=True)),
                ('cnpj', models.CharField(blank=True, help_text='Apenas dígitos. Sem máscara.', max_length=14)),
                ('timezone', models.CharField(default='America/Sao_Paulo', help_text='Timezone IANA. Lembretes e horário comercial respeitam este valor.', max_length=64)),
                ('horario_comercial', models.JSONField(blank=True, default=dict, help_text="Janelas de atendimento humano por dia da semana. Formato: {'seg': [['08:00', '18:00']], 'sab': [['08:00', '12:00']], ...}. Fora dessas janelas, o bot responde sozinho mas não escala handoff.")),
                ('ativa', models.BooleanField(default=True, help_text='Quando False, webhooks são aceitos mas não disparam tasks. Soft-disable para clientes em débito ou em onboarding.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'clínica',
                'verbose_name_plural': 'clínicas',
                'db_table': 'clinicas',
                'ordering': ['nome'],
            },
        ),
    ]
