# Generated by Django 6.0.4 on 2026-04-29 00:40

import apps.clinics.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0001_initial"),
        ("core", "0001_rls_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicaCanal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("whatsapp_evolution", "WhatsApp via Evolution API"),
                            ("whatsapp_cloud", "WhatsApp Cloud API (Meta)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "numero_e164",
                    models.CharField(
                        db_index=True,
                        help_text="Número no formato E.164, ex.: +5511999999999",
                        max_length=16,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Credenciais/IDs do provedor. Evolution: {'instance_id': ..., 'token': ...}. Cloud: {'phone_number_id': ..., 'business_account_id': ...}.",
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        default=apps.clinics.models._gerar_webhook_secret,
                        help_text="Segredo HMAC do webhook deste canal. Auto-gerado na criação. Rotacionar = setar em branco e salvar.",
                        max_length=64,
                    ),
                ),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "canal da clínica",
                "verbose_name_plural": "canais da clínica",
                "db_table": "clinica_canais",
                "indexes": [
                    models.Index(
                        fields=["clinica", "ativo"], name="canal_clinica_ativo_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinica", "tipo"),
                        name="canal_unico_por_tipo_por_clinica",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicaPolitica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("chave", models.CharField(max_length=100)),
                (
                    "valor",
                    models.JSONField(
                        help_text="Tipo varia por chave (int, str, bool, list, dict)."
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "política da clínica",
                "verbose_name_plural": "políticas da clínica",
                "db_table": "clinica_politicas",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinica", "chave"),
                        name="politica_unica_por_chave_por_clinica",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('clinica_canais');",
            reverse_sql="SELECT drop_rls_policy('clinica_canais');",
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('clinica_politicas');",
            reverse_sql="SELECT drop_rls_policy('clinica_politicas');",
        ),
    ]
