# Generated by Django 6.0.4 on 2026-04-29 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0002_clinicacanal_clinicapolitica"),
        ("conversations", "0001_initial"),
        ("core", "0002_grants_app_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoBot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("mensagem_recebida", "Mensagem recebida"),
                            ("resposta_enviada", "Resposta enviada"),
                            ("tool_call", "Chamada de ferramenta"),
                            ("erro", "Erro"),
                            ("transicao_status", "Transição de status"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "dados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conteúdo variável por tipo (ver docstring do modelo).",
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null para eventos globais (sem conversa associada). SET_NULL para preservar evento mesmo se a conversa for deletada — auditoria não some junto com o dado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="conversations.conversa",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento do bot",
                "verbose_name_plural": "eventos do bot",
                "db_table": "eventos_bot",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["clinica", "-criado_em"],
                        name="evento_clinica_recente_idx",
                    ),
                    models.Index(
                        condition=models.Q(("conversa__isnull", False)),
                        fields=["conversa", "-criado_em"],
                        name="evento_conversa_recente_idx",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('eventos_bot');",
            reverse_sql="SELECT drop_rls_policy('eventos_bot');",
        ),
    ]
