# Generated by Django 6.0.4 on 2026-04-29 00:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0002_clinicacanal_clinicapolitica"),
        ("core", "0001_rls_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "telefone_e164",
                    models.CharField(
                        db_index=True,
                        help_text="Formato E.164 com '+' e código país, ex.: +5511999999999.",
                        max_length=16,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Resolvido do `pushName` do WhatsApp na primeira mensagem. Bot pode pedir confirmação/correção depois.",
                        max_length=200,
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Apenas dígitos, sem máscara. Opcional por padrão — torna-se obrigatório se a política `cpf_obrigatorio` da clínica for True.",
                        max_length=14,
                        null=True,
                    ),
                ),
                (
                    "lgpd_aceito_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Timestamp do aceite do aviso LGPD. Enquanto null, o bot apresenta o texto da política `lgpd_texto` antes de qualquer outra interação.",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados auxiliares: `pushName` original do WhatsApp, tags de segmentação, anotações livres.",
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "paciente",
                "verbose_name_plural": "pacientes",
                "db_table": "pacientes",
                "indexes": [
                    models.Index(
                        condition=models.Q(("cpf__isnull", False)),
                        fields=["cpf"],
                        name="paciente_cpf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinica", "telefone_e164"),
                        name="paciente_unico_por_telefone_por_clinica",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('pacientes');",
            reverse_sql="SELECT drop_rls_policy('pacientes');",
        ),
    ]
