# Generated by Django 6.0.4 on 2026-04-29 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0002_clinicacanal_clinicapolitica"),
        ("core", "0001_rls_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "especialidade",
                "verbose_name_plural": "especialidades",
                "db_table": "especialidades",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=200)),
                (
                    "crm",
                    models.CharField(
                        help_text="Formato 'NÚMERO/UF', ex.: '123456/SP'.",
                        max_length=20,
                    ),
                ),
                (
                    "duracao_consulta_min",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Duração padrão da consulta em minutos. Usado para gerar slots.",
                    ),
                ),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
                (
                    "especialidade",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bloqueia deletar especialidade que ainda tem médico.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.especialidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "médico",
                "verbose_name_plural": "médicos",
                "db_table": "medicos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Convenio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "convênio",
                "verbose_name_plural": "convênios",
                "db_table": "convenios",
                "ordering": ["nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinica", "nome"), name="convenio_unico_por_clinica"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="especialidade",
            constraint=models.UniqueConstraint(
                fields=("clinica", "nome"), name="especialidade_unica_por_clinica"
            ),
        ),
        migrations.AddIndex(
            model_name="medico",
            index=models.Index(
                fields=["clinica", "ativo", "especialidade"],
                name="medico_clinica_ativo_esp_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="medico",
            constraint=models.UniqueConstraint(
                fields=("clinica", "crm"), name="medico_crm_unico_por_clinica"
            ),
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('especialidades');",
            reverse_sql="SELECT drop_rls_policy('especialidades');",
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('medicos');",
            reverse_sql="SELECT drop_rls_policy('medicos');",
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('convenios');",
            reverse_sql="SELECT drop_rls_policy('convenios');",
        ),
    ]
