# Generated by Django 6.0.4 on 2026-04-29 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("clinics", "0002_clinicacanal_clinicapolitica"),
        ("core", "0001_rls_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicoConvenio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "preco_consulta_centavos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Valor em centavos (sem decimal). Null = usa preço default da clínica/convênio definido em política.",
                        null=True,
                    ),
                ),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
                (
                    "convenio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.convenio",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.medico",
                    ),
                ),
            ],
            options={
                "verbose_name": "convênio do médico",
                "verbose_name_plural": "convênios dos médicos",
                "db_table": "medico_convenios",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("medico", "convenio"), name="medico_convenio_unico"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicoDisponibilidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda"),
                            (1, "Terça"),
                            (2, "Quarta"),
                            (3, "Quinta"),
                            (4, "Sexta"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                (
                    "inicio",
                    models.TimeField(
                        help_text="Hora local da clínica (timezone do tenant)."
                    ),
                ),
                ("fim", models.TimeField()),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.medico",
                    ),
                ),
            ],
            options={
                "verbose_name": "disponibilidade do médico",
                "verbose_name_plural": "disponibilidades dos médicos",
                "db_table": "medico_disponibilidades",
                "ordering": ["medico", "dia_semana", "inicio"],
                "indexes": [
                    models.Index(
                        fields=["medico", "dia_semana"],
                        name="disponibilidade_medico_dia_idx",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('medico_convenios');",
            reverse_sql="SELECT drop_rls_policy('medico_convenios');",
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('medico_disponibilidades');",
            reverse_sql="SELECT drop_rls_policy('medico_disponibilidades');",
        ),
    ]
