# Generated by Django 6.0.4 on 2026-04-29 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0002_clinicacanal_clinicapolitica"),
        ("core", "0002_grants_app_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("whatsapp_text", "WhatsApp texto"),
                            ("whatsapp_template", "WhatsApp template"),
                            ("whatsapp_media", "WhatsApp mídia"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Dados específicos do tipo: destino, corpo, template, media URL etc. Inclui `mensagem_id` quando há linha em `mensagens` para atualizar com o `external_id` retornado pelo provedor."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("enviado", "Enviado"),
                            ("falha", "Falha (com retry)"),
                            ("descartado", "Descartado (sem retry)"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=16,
                    ),
                ),
                (
                    "tentativas",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantas vezes a task tentou enviar."
                    ),
                ),
                (
                    "proxima_em",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Quando a task pode tentar enviar de novo. Backoff exponencial sobe esse valor a cada falha.",
                    ),
                ),
                (
                    "enviado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp do envio bem-sucedido.",
                        null=True,
                    ),
                ),
                (
                    "erro_ultimo",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem do último erro do provedor.",
                        null=True,
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "item da outbox",
                "verbose_name_plural": "outbox",
                "db_table": "outbox",
                "ordering": ["proxima_em"],
                "indexes": [
                    models.Index(
                        fields=["clinica", "status", "proxima_em"],
                        name="outbox_clinica_pronto_idx",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('outbox');",
            reverse_sql="SELECT drop_rls_policy('outbox');",
        ),
    ]
