# Generated by Django 6.0.4 on 2026-04-29 01:02

import apps.appointments.models
import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_medicoconvenio_medicodisponibilidade"),
        ("clinics", "0002_clinicacanal_clinicapolitica"),
        ("patients", "0001_initial"),
        ("core", "0002_grants_app_roles"),
    ]

    operations = [
        # Exclusion constraint usa operador `=` em coluna não-range
        # (medico_id) junto com `&&` em range (tstzrange). Postgres só
        # permite `=` em índice GIST se a extension `btree_gist` estiver
        # instalada — daí o CREATE EXTENSION antes do CreateModel.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gist;",
            # Não removemos a extension no rollback — outras tabelas
            # podem depender dela (ex.: pgvector usa). Removê-la
            # silenciosamente ia quebrar coisas distantes.
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("inicio_em", models.DateTimeField(db_index=True)),
                (
                    "fim_em",
                    models.DateTimeField(
                        help_text="Calculado pelo bot a partir de `inicio_em + medico.duracao_consulta_min`. Explicito no schema porque a constraint precisa do range."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("realizado", "Realizado"),
                            ("cancelado", "Cancelado"),
                            ("nao_compareceu", "Não compareceu"),
                        ],
                        db_index=True,
                        default="agendado",
                        max_length=16,
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("bot", "Bot"),
                            ("humano", "Humano"),
                            ("import", "Importação"),
                        ],
                        default="bot",
                        help_text="Por onde o agendamento entrou no sistema.",
                        max_length=16,
                    ),
                ),
                (
                    "external_event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID do evento no calendário externo (Google/Outlook).",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "external_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google_calendar", "Google Calendar"),
                            ("outlook", "Outlook"),
                            ("apple", "Apple"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "cancelado_motivo",
                    models.TextField(
                        blank=True,
                        help_text="Texto livre do motivo de cancelamento (paciente ou clínica).",
                        null=True,
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
                (
                    "convenio",
                    models.ForeignKey(
                        help_text="PROTECT — não permite deletar convênio que tem agendamento.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.convenio",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="patients.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "agendamento",
                "verbose_name_plural": "agendamentos",
                "db_table": "agendamentos",
                "ordering": ["-inicio_em"],
                "indexes": [
                    models.Index(
                        fields=["clinica", "inicio_em", "status"],
                        name="agend_clinica_data_status_idx",
                    ),
                    models.Index(
                        fields=["paciente", "status"],
                        name="agend_paciente_status_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("inicio_em__lt", models.F("fim_em"))),
                        name="agendamento_inicio_antes_de_fim",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("status", "cancelado"), _negated=True),
                        expressions=[
                            ("medico", "="),
                            (
                                apps.appointments.models.TstzRange(
                                    "inicio_em", "fim_em"
                                ),
                                "&&",
                            ),
                        ],
                        name="agendamento_sem_overlap_por_medico",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('agendamentos');",
            reverse_sql="SELECT drop_rls_policy('agendamentos');",
        ),
    ]
