# Generated by Django 6.0.4 on 2026-04-29 01:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0002_clinicacanal_clinicapolitica"),
        ("patients", "0001_initial"),
        ("core", "0002_grants_app_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("bot", "Bot ativo"),
                            ("handoff_aguardando", "Aguardando atendente"),
                            ("handoff_ativo", "Atendente conduzindo"),
                            ("encerrada", "Encerrada"),
                        ],
                        db_index=True,
                        default="bot",
                        max_length=24,
                    ),
                ),
                (
                    "contexto",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Estado transitório do fluxo bot: intenção detectada, slot fillers, flags. Não é histórico de mensagens.",
                    ),
                ),
                ("encerrado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "canal",
                    models.ForeignKey(
                        help_text="Canal pelo qual a conversa está acontecendo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="clinics.clinicacanal",
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="patients.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversa",
                "verbose_name_plural": "conversas",
                "db_table": "conversas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Handoff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "gatilho",
                    models.CharField(
                        choices=[
                            ("pedido_explicito", "Paciente pediu humano"),
                            ("confianca_baixa", "Bot incerto"),
                            ("urgencia_medica", "Sinal de urgência"),
                            ("reclamacao", "Reclamação detectada"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "aceito_por",
                    models.CharField(
                        blank=True,
                        help_text="Identificador do atendente que assumiu (livre por enquanto).",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "encerrado_em",
                    models.DateTimeField(
                        blank=True, help_text="Null = handoff em aberto.", null=True
                    ),
                ),
                (
                    "resolucao",
                    models.TextField(
                        blank=True,
                        help_text="Resumo livre de como o atendimento foi resolvido.",
                        null=True,
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="conversations.conversa",
                    ),
                ),
            ],
            options={
                "verbose_name": "handoff",
                "verbose_name_plural": "handoffs",
                "db_table": "handoffs",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "direcao",
                    models.CharField(
                        choices=[
                            ("entrada", "Recebida (paciente → sistema)"),
                            ("saida", "Enviada (sistema → paciente)"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "remetente",
                    models.CharField(
                        help_text="Identificador de quem enviou: E.164 do paciente em entradas; nome do bot ou ID do atendente em saídas.",
                        max_length=256,
                    ),
                ),
                ("conteudo", models.TextField(help_text="Texto da mensagem.")),
                (
                    "payload_raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Payload bruto do provedor (Evolution/Cloud) para debug.",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID atribuído pelo provedor. Null em mensagens geradas localmente que ainda não foram enviadas.",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "canal",
                    models.ForeignKey(
                        help_text="Redundante (mesmo canal da conversa) — preenchido para queries de idempotência sem JOIN.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="clinics.clinicacanal",
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinica",
                    ),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="conversations.conversa",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem",
                "verbose_name_plural": "mensagens",
                "db_table": "mensagens",
                "ordering": ["criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="conversa",
            index=models.Index(
                fields=["clinica", "status"], name="conv_clinica_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversa",
            index=models.Index(
                fields=["paciente", "-criado_em"], name="conv_paciente_recente_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handoff",
            index=models.Index(
                fields=["clinica", "-criado_em"], name="handoff_clinica_recente_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handoff",
            index=models.Index(fields=["conversa"], name="handoff_conversa_idx"),
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(
                fields=["conversa", "criado_em"], name="msg_conversa_data_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mensagem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("canal", "external_id"),
                name="msg_canal_external_id_unico_se_presente",
            ),
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('conversas');",
            reverse_sql="SELECT drop_rls_policy('conversas');",
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('mensagens');",
            reverse_sql="SELECT drop_rls_policy('mensagens');",
        ),
        migrations.RunSQL(
            sql="SELECT apply_rls_policy('handoffs');",
            reverse_sql="SELECT drop_rls_policy('handoffs');",
        ),
    ]
